#############################################################################
# Makefile for building: libQKeySequenceOverride.so.1.0.0
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  override.pro
# Template: lib
# Command: /usr/local/lib/qt5/bin/qmake -o Makefile override.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -pthread -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -pthread -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../../local/include/qt5/QtCore -I../../../../local/include/qt5/QtGui -I../../../../local/include/qt5/QtWidgets -I../../../../local/include/qt5 -I. -I../../../../local/include/libdrm -I../../../../local/include -I../../../../local/lib/qt5/mkspecs/freebsd-clang
QMAKE         = /usr/local/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QKeySequenceOverride1.0.0
DISTDIR = /usr/home/user/helloSystem/OverrideQtSplashscreen/.tmp/QKeySequenceOverride1.0.0
LINK          = clang++
LFLAGS        = -pthread -Wl,-rpath,/usr/local/lib/qt5 -shared -Wl,-soname,libQKeySequenceOverride.so.1
LIBS          = $(SUBLIBS) -L/usr/local/lib /usr/local/lib/qt5/libQt5Gui.so /usr/local/lib/qt5/libQt5Core.so -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = override.cpp 
OBJECTS       = override.o
DIST          = ../../../../local/lib/qt5/mkspecs/features/spec_pre.prf \
		../../../../local/lib/qt5/mkspecs/common/unix.conf \
		../../../../local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		../../../../local/lib/qt5/mkspecs/common/sanitize.conf \
		../../../../local/lib/qt5/mkspecs/common/gcc-base.conf \
		../../../../local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../../local/lib/qt5/mkspecs/common/clang.conf \
		../../../../local/lib/qt5/mkspecs/qconfig.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Attica.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Baloo.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KActivities.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KArchive.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KAuth.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KAuthCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KBookmarks.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCalendarCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCMUtils.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCodecs.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCompletion.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KConfigCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KConfigGui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCrash.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KDeclarative.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KEmoticons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KI18n.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIconThemes.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIdleTime.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOGui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Kirigami2.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KItemModels.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KItemViews.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNewStuff.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNotifications.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNTLM.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KParts.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KPlotting.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KQuickImageEditor.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KScreen.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KService.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWallet.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KXmlGui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdf.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_repparser.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webview.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Qt5Keychain.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_QuickAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Solid.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_SonnetCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_SonnetUi.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Syndication.pri \
		../../../../local/lib/qt5/mkspecs/features/qt_functions.prf \
		../../../../local/lib/qt5/mkspecs/features/qt_config.prf \
		../../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		../../../../local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		../../../../local/lib/qt5/mkspecs/features/toolchain.prf \
		../../../../local/lib/qt5/mkspecs/features/default_pre.prf \
		../../../../local/lib/qt5/mkspecs/features/resolve_config.prf \
		../../../../local/lib/qt5/mkspecs/features/default_post.prf \
		../../../../local/lib/qt5/mkspecs/features/warn_on.prf \
		../../../../local/lib/qt5/mkspecs/features/qt.prf \
		../../../../local/lib/qt5/mkspecs/features/resources_functions.prf \
		../../../../local/lib/qt5/mkspecs/features/resources.prf \
		../../../../local/lib/qt5/mkspecs/features/moc.prf \
		../../../../local/lib/qt5/mkspecs/features/unix/opengl.prf \
		../../../../local/lib/qt5/mkspecs/features/unix/thread.prf \
		../../../../local/lib/qt5/mkspecs/features/qmake_use.prf \
		../../../../local/lib/qt5/mkspecs/features/file_copies.prf \
		../../../../local/lib/qt5/mkspecs/features/testcase_targets.prf \
		../../../../local/lib/qt5/mkspecs/features/exceptions.prf \
		../../../../local/lib/qt5/mkspecs/features/yacc.prf \
		../../../../local/lib/qt5/mkspecs/features/lex.prf \
		override.pro  override.cpp
QMAKE_TARGET  = QKeySequenceOverride
DESTDIR       = 
TARGET        = libQKeySequenceOverride.so.1.0.0
TARGETA       = libQKeySequenceOverride.a
TARGET0       = libQKeySequenceOverride.so
TARGETD       = libQKeySequenceOverride.so.1.0.0
TARGET1       = libQKeySequenceOverride.so.1
TARGET2       = libQKeySequenceOverride.so.1.0


first: all
####### Build rules

libQKeySequenceOverride.so.1.0.0:  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-: $(TARGET) $(TARGET0)
	-: $(TARGET) $(TARGET1)
	-: $(TARGET) $(TARGET2)



staticlib: libQKeySequenceOverride.a

libQKeySequenceOverride.a:  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: override.pro ../../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf ../../../../local/lib/qt5/mkspecs/features/spec_pre.prf \
		../../../../local/lib/qt5/mkspecs/common/unix.conf \
		../../../../local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		../../../../local/lib/qt5/mkspecs/common/sanitize.conf \
		../../../../local/lib/qt5/mkspecs/common/gcc-base.conf \
		../../../../local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../../local/lib/qt5/mkspecs/common/clang.conf \
		../../../../local/lib/qt5/mkspecs/qconfig.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Attica.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Baloo.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KActivities.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KArchive.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KAuth.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KAuthCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KBookmarks.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCalendarCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCMUtils.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCodecs.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCompletion.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KConfigCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KConfigGui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KCrash.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KDeclarative.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KEmoticons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KI18n.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIconThemes.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIdleTime.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOGui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Kirigami2.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KItemModels.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KItemViews.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNewStuff.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNotifications.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KNTLM.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KParts.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KPlotting.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KQuickImageEditor.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KScreen.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KService.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWallet.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_KXmlGui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdf.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_repparser.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webview.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Qt5Keychain.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_QuickAddons.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Solid.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_SonnetCore.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_SonnetUi.pri \
		../../../../local/lib/qt5/mkspecs/modules/qt_Syndication.pri \
		../../../../local/lib/qt5/mkspecs/features/qt_functions.prf \
		../../../../local/lib/qt5/mkspecs/features/qt_config.prf \
		../../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		../../../../local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		../../../../local/lib/qt5/mkspecs/features/toolchain.prf \
		../../../../local/lib/qt5/mkspecs/features/default_pre.prf \
		../../../../local/lib/qt5/mkspecs/features/resolve_config.prf \
		../../../../local/lib/qt5/mkspecs/features/default_post.prf \
		../../../../local/lib/qt5/mkspecs/features/warn_on.prf \
		../../../../local/lib/qt5/mkspecs/features/qt.prf \
		../../../../local/lib/qt5/mkspecs/features/resources_functions.prf \
		../../../../local/lib/qt5/mkspecs/features/resources.prf \
		../../../../local/lib/qt5/mkspecs/features/moc.prf \
		../../../../local/lib/qt5/mkspecs/features/unix/opengl.prf \
		../../../../local/lib/qt5/mkspecs/features/unix/thread.prf \
		../../../../local/lib/qt5/mkspecs/features/qmake_use.prf \
		../../../../local/lib/qt5/mkspecs/features/file_copies.prf \
		../../../../local/lib/qt5/mkspecs/features/testcase_targets.prf \
		../../../../local/lib/qt5/mkspecs/features/exceptions.prf \
		../../../../local/lib/qt5/mkspecs/features/yacc.prf \
		../../../../local/lib/qt5/mkspecs/features/lex.prf \
		override.pro
	$(QMAKE) -o Makefile override.pro
../../../../local/lib/qt5/mkspecs/features/spec_pre.prf:
../../../../local/lib/qt5/mkspecs/common/unix.conf:
../../../../local/lib/qt5/mkspecs/common/bsd/bsd.conf:
../../../../local/lib/qt5/mkspecs/common/sanitize.conf:
../../../../local/lib/qt5/mkspecs/common/gcc-base.conf:
../../../../local/lib/qt5/mkspecs/common/gcc-base-unix.conf:
../../../../local/lib/qt5/mkspecs/common/clang.conf:
../../../../local/lib/qt5/mkspecs/qconfig.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_Attica.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_Baloo.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_core.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_dbus.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_declarative.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_gui.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_network.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_opengl.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_config_widgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KActivities.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KArchive.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KAuth.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KAuthCore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KBookmarks.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KCalendarCore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KCMUtils.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KCodecs.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KCompletion.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KConfigCore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KConfigGui.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KCrash.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KDeclarative.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KEmoticons.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KI18n.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KIconThemes.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KIdleTime.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KIOCore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KIOGui.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_Kirigami2.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KItemModels.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KItemViews.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KNewStuff.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KNotifications.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KNTLM.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KParts.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KPlotting.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KQuickImageEditor.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KScreen.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KService.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KWallet.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_KXmlGui.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_charts.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_core.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_gamepad.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_help.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_location.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_network.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdf.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdf_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3d.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3drender.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_repparser.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_script.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_scxml.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webview.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_webview_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_Qt5Keychain.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_QuickAddons.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_Solid.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_SonnetCore.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_SonnetUi.pri:
../../../../local/lib/qt5/mkspecs/modules/qt_Syndication.pri:
../../../../local/lib/qt5/mkspecs/features/qt_functions.prf:
../../../../local/lib/qt5/mkspecs/features/qt_config.prf:
../../../../local/lib/qt5/mkspecs/freebsd-clang/qmake.conf:
../../../../local/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../local/lib/qt5/mkspecs/features/exclusive_builds.prf:
../../../../local/lib/qt5/mkspecs/features/toolchain.prf:
../../../../local/lib/qt5/mkspecs/features/default_pre.prf:
../../../../local/lib/qt5/mkspecs/features/resolve_config.prf:
../../../../local/lib/qt5/mkspecs/features/default_post.prf:
../../../../local/lib/qt5/mkspecs/features/warn_on.prf:
../../../../local/lib/qt5/mkspecs/features/qt.prf:
../../../../local/lib/qt5/mkspecs/features/resources_functions.prf:
../../../../local/lib/qt5/mkspecs/features/resources.prf:
../../../../local/lib/qt5/mkspecs/features/moc.prf:
../../../../local/lib/qt5/mkspecs/features/unix/opengl.prf:
../../../../local/lib/qt5/mkspecs/features/unix/thread.prf:
../../../../local/lib/qt5/mkspecs/features/qmake_use.prf:
../../../../local/lib/qt5/mkspecs/features/file_copies.prf:
../../../../local/lib/qt5/mkspecs/features/testcase_targets.prf:
../../../../local/lib/qt5/mkspecs/features/exceptions.prf:
../../../../local/lib/qt5/mkspecs/features/yacc.prf:
../../../../local/lib/qt5/mkspecs/features/lex.prf:
override.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile override.pro

qmake_all: FORCE


all: Makefile libQKeySequenceOverride.so.1.0.0

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../local/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents override.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../local/lib/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h ../../../../local/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

override.o: override.cpp ../../../../local/include/qt5/QtWidgets/QApplication \
		../../../../local/include/qt5/QtWidgets/qapplication.h \
		../../../../local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		../../../../local/include/qt5/QtGui/qtguiglobal.h \
		../../../../local/include/qt5/QtCore/qglobal.h \
		../../../../local/include/qt5/QtCore/qconfig-bootstrapped.h \
		../../../../local/include/qt5/QtCore/qconfig.h \
		../../../../local/include/qt5/QtCore/qconfig-modules.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-core.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-dbus.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-declarative.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-gui.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-network.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-opengl.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		../../../../local/include/qt5/QtCore/modules/qconfig-widgets.h \
		../../../../local/include/qt5/QtCore/qtcore-config.h \
		../../../../local/include/qt5/QtCore/qsystemdetection.h \
		../../../../local/include/qt5/QtCore/qprocessordetection.h \
		../../../../local/include/qt5/QtCore/qcompilerdetection.h \
		../../../../local/include/qt5/QtCore/qtypeinfo.h \
		../../../../local/include/qt5/QtCore/qsysinfo.h \
		../../../../local/include/qt5/QtCore/qlogging.h \
		../../../../local/include/qt5/QtCore/qflags.h \
		../../../../local/include/qt5/QtCore/qatomic.h \
		../../../../local/include/qt5/QtCore/qbasicatomic.h \
		../../../../local/include/qt5/QtCore/qatomic_bootstrap.h \
		../../../../local/include/qt5/QtCore/qgenericatomic.h \
		../../../../local/include/qt5/QtCore/qatomic_cxx11.h \
		../../../../local/include/qt5/QtCore/qatomic_msvc.h \
		../../../../local/include/qt5/QtCore/qglobalstatic.h \
		../../../../local/include/qt5/QtCore/qmutex.h \
		../../../../local/include/qt5/QtCore/qnumeric.h \
		../../../../local/include/qt5/QtCore/qversiontagging.h \
		../../../../local/include/qt5/QtGui/qtgui-config.h \
		../../../../local/include/qt5/QtWidgets/qtwidgets-config.h \
		../../../../local/include/qt5/QtCore/qcoreapplication.h \
		../../../../local/include/qt5/QtCore/qstring.h \
		../../../../local/include/qt5/QtCore/qchar.h \
		../../../../local/include/qt5/QtCore/qbytearray.h \
		../../../../local/include/qt5/QtCore/qrefcount.h \
		../../../../local/include/qt5/QtCore/qnamespace.h \
		../../../../local/include/qt5/QtCore/qarraydata.h \
		../../../../local/include/qt5/QtCore/qstringliteral.h \
		../../../../local/include/qt5/QtCore/qstringalgorithms.h \
		../../../../local/include/qt5/QtCore/qstringview.h \
		../../../../local/include/qt5/QtCore/qstringbuilder.h \
		../../../../local/include/qt5/QtCore/qobject.h \
		../../../../local/include/qt5/QtCore/qobjectdefs.h \
		../../../../local/include/qt5/QtCore/qobjectdefs_impl.h \
		../../../../local/include/qt5/QtCore/qlist.h \
		../../../../local/include/qt5/QtCore/qalgorithms.h \
		../../../../local/include/qt5/QtCore/qiterator.h \
		../../../../local/include/qt5/QtCore/qhashfunctions.h \
		../../../../local/include/qt5/QtCore/qpair.h \
		../../../../local/include/qt5/QtCore/qvector.h \
		../../../../local/include/qt5/QtCore/qcontainertools_impl.h \
		../../../../local/include/qt5/QtCore/qpoint.h \
		../../../../local/include/qt5/QtCore/qbytearraylist.h \
		../../../../local/include/qt5/QtCore/qstringlist.h \
		../../../../local/include/qt5/QtCore/qregexp.h \
		../../../../local/include/qt5/QtCore/qstringmatcher.h \
		../../../../local/include/qt5/QtCore/qcoreevent.h \
		../../../../local/include/qt5/QtCore/qscopedpointer.h \
		../../../../local/include/qt5/QtCore/qmetatype.h \
		../../../../local/include/qt5/QtCore/qvarlengtharray.h \
		../../../../local/include/qt5/QtCore/qcontainerfwd.h \
		../../../../local/include/qt5/QtCore/qobject_impl.h \
		../../../../local/include/qt5/QtCore/qeventloop.h \
		../../../../local/include/qt5/QtGui/qwindowdefs.h \
		../../../../local/include/qt5/QtGui/qwindowdefs_win.h \
		../../../../local/include/qt5/QtCore/qsize.h \
		../../../../local/include/qt5/QtCore/qmargins.h \
		../../../../local/include/qt5/QtGui/qcursor.h \
		../../../../local/include/qt5/QtWidgets/qdesktopwidget.h \
		../../../../local/include/qt5/QtWidgets/qwidget.h \
		../../../../local/include/qt5/QtGui/qpaintdevice.h \
		../../../../local/include/qt5/QtCore/qrect.h \
		../../../../local/include/qt5/QtGui/qpalette.h \
		../../../../local/include/qt5/QtGui/qcolor.h \
		../../../../local/include/qt5/QtGui/qrgb.h \
		../../../../local/include/qt5/QtGui/qrgba64.h \
		../../../../local/include/qt5/QtGui/qbrush.h \
		../../../../local/include/qt5/QtGui/qmatrix.h \
		../../../../local/include/qt5/QtGui/qpolygon.h \
		../../../../local/include/qt5/QtGui/qregion.h \
		../../../../local/include/qt5/QtCore/qdatastream.h \
		../../../../local/include/qt5/QtCore/qiodevice.h \
		../../../../local/include/qt5/QtCore/qline.h \
		../../../../local/include/qt5/QtGui/qtransform.h \
		../../../../local/include/qt5/QtGui/qimage.h \
		../../../../local/include/qt5/QtGui/qpixelformat.h \
		../../../../local/include/qt5/QtGui/qpixmap.h \
		../../../../local/include/qt5/QtCore/qsharedpointer.h \
		../../../../local/include/qt5/QtCore/qshareddata.h \
		../../../../local/include/qt5/QtCore/qhash.h \
		../../../../local/include/qt5/QtCore/qsharedpointer_impl.h \
		../../../../local/include/qt5/QtGui/qfont.h \
		../../../../local/include/qt5/QtGui/qfontmetrics.h \
		../../../../local/include/qt5/QtGui/qfontinfo.h \
		../../../../local/include/qt5/QtWidgets/qsizepolicy.h \
		../../../../local/include/qt5/QtGui/qkeysequence.h \
		../../../../local/include/qt5/QtGui/qevent.h \
		../../../../local/include/qt5/QtCore/qvariant.h \
		../../../../local/include/qt5/QtCore/qmap.h \
		../../../../local/include/qt5/QtCore/qdebug.h \
		../../../../local/include/qt5/QtCore/qtextstream.h \
		../../../../local/include/qt5/QtCore/qlocale.h \
		../../../../local/include/qt5/QtCore/qset.h \
		../../../../local/include/qt5/QtCore/qcontiguouscache.h \
		../../../../local/include/qt5/QtCore/qurl.h \
		../../../../local/include/qt5/QtCore/qurlquery.h \
		../../../../local/include/qt5/QtCore/qfile.h \
		../../../../local/include/qt5/QtCore/qfiledevice.h \
		../../../../local/include/qt5/QtGui/qvector2d.h \
		../../../../local/include/qt5/QtGui/qtouchdevice.h \
		../../../../local/include/qt5/QtGui/qguiapplication.h \
		../../../../local/include/qt5/QtGui/qinputmethod.h \
		../../../../local/include/qt5/QtGui/QKeySequence \
		../../../../local/include/qt5/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o override.o override.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

